#!/usr/bin/env python3

from dirlist_cmd import dirlist_cmd  # type: ignore
import sys

if __name__ == "__main__":
    try:
        dirlist_cmd()
    except BrokenPipeError as e:
        print(f"fisken, {e}", file=sys.stderr)
#        sys.exit(1)
