[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hostname = "*"
whoami = "*"
argh = "*"

[[bin]]
name = "my_prompt"
path = "src/my_prompt.rs"
