export MONKEY=$HOME/.config/monkey_banana_party_pack

pushd "$MONKEY/bash" > /dev/null

# Enable minor spell checking for directory names.
shopt -s cdspell

# If a command name names a directory, change to that directory.
shopt -s autocd

# Add multiline commands to history
shopt -s cmdhist

# Hostname completion after @
shopt -s hostcomplete

# Set PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.config/monkey_banana_party_pack/bin:$PATH
export PATH=$HOME/.config/monkey_banana_party_pack/systool:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

# Editor settings
export EDITOR=nvim

# Misc aliases
alias cal='cal -mw'
alias top='top -d1'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'        # NOTE: Capital 'I' only prompts if more than tree files are removed.
alias ln='ln -i'
alias f='find'
alias open='xdg-open'
alias tp='trash-put'
alias tl='trash-list'
alias tr='trash-restore'
alias t='tmux'
alias nv='nvim'

# Disable ctrl-s freezing
stty -ixon

# Clear terminal on CTRL-L
bind -x '"\C-l": clear;'

# Clear the prompt first.
PROMPT_COMMAND=""

source prompt.sh
source history.sh
source terminal.sh
source anki.sh
source fzf.sh
source ls.sh
source /usr/share/lf/lfcd.sh
[[ -r "/usr/share/z/z.sh" ]] && source /usr/share/z/z.sh

# This must be added last so that the exit code is saved before any other
# commands clobber it.
PROMPT_COMMAND="OK=\$?; $PROMPT_COMMAND"

# Workaround for bug in QT (corrupts GUI in keepassxc)
export QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor

popd > /dev/null
