# Setup the environment for the entire session.

# Set PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.config/monkey_banana_party_pack/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

# Editor settings
export EDITOR=nvim

# Workaround for bug in QT (corrupts GUI in keepassxc)
export QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor

# This workaround fixes wierd graphical glitches in the GUI.
export ANKI_NOHIGHDPI=1

if [ "$(tty)" = "/dev/tty1" ]; then
    # Disable history file in order to prevent truncating it.
    unset HISTFILE
    echo "Console login. Run 'startx'"
elif [ "$(tty)" = "/dev/tty2" ]; then
    # Disable history file in order to prevent truncating it.
    unset HISTFILE
    echo "Console login. Run 'startx'"
else
    [[ -f ~/.bashrc ]] && . ~/.bashrc
fi
