# Set PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.config/monkey_banana_party_pack/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

# Editor settings
export EDITOR=nvim

# Workaround for bug in QT (corrupts GUI in keepassxc)
export QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor

# This workaround fixes wierd graphical glitches in the GUI.
export ANKI_NOHIGHDPI=1

[[ -f ~/.bashrc ]] && . ~/.bashrc
